using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExampleGenerator
{
    [Generator]
    public class ExampleGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("Generated.cs",
                SourceText.From("// <auto-generated />\n" +
                                "\n" +
                                "namespace Example.Generated;\n" +
                                "\n" +
                                "public sealed record GeneratedClass(string Name);\n", Encoding.UTF8));
        }
    }
}
